---
- name: Launch database container
  docker_container:
    name: my_database
    image: foderac3/tp-devops-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-db
    networks:
      - name: my_app_network