---
- name: Create Docker network
  docker_network:
    name: my_app_network
    state: present
    driver: bridge
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Remplacez si votre interpréteur Python est différent
